[Draw]
logy: 1
withSF: 0
withChi: 0
offset: 3
save: 0
lc: 46, 8, 9

[g0]
logy: 1
ADWA: ./Inputs/gs_ADWA_newFront/fort.202

[g1]
ADWA: ./Inputs/gs_ADWA_newFront/fort.203

[v0]
ADWA: ./Inputs/gs_ADWA_newFront/fort.206

[v1]

[v2]

[v3]

[v4]

[v5]

[v6]
